#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation

#homepage:
#  path: /
#  defaults: { _controller: AppBundle:Default:index }
#
#constraint:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:paramConstraint }
#  requirements:
#    param: '\d+'
#
#param_homepage:
#  path: /{param}/
#  defaults: { _controller: AppBundle:Default:param }

request_querystring:
  path: /querystring/
  defaults: { _controller: AppBundle:Default:requestQuerystring }

request_post:
  path: /post/
  defaults: { _controller: AppBundle:Default:requestPost }
  methods: [POST]

#http://127.0.0.1:8000/rest
calculator_rest:
    path: /rest
    defaults: { _controller: AppBundle:Substract:substract }
    methods: [POST]

#http://127.0.0.1:8000/add/2/2
calculator_add:
  path: /add/{param1}/{param2}/
  defaults: { _controller: AppBundle:Add:add }
  methods: [GET]
  requirements:
    param1: '\d+'
    param2: '\d+'

#http://127.0.0.1:8000/multiply?param1=2&param2=2
calculator_mul:
    path: /multiply
    defaults: { _controller: AppBundle:Multiply:multiply }
    methods: [GET]

#http://127.0.0.1:8000/divide/2?param2=2
calculator_div:
    path: /divide/{param1}
    defaults: { _controller: AppBundle:Divide:divide }
    methods: [GET]
    requirements:
      param1: '\d+'